# coding agent with ollama to automatically generate code for a given
# task or improve existing code

# 1. provide a task description and a start location
# - define coding environment file access

# 2. create ollama coding agent conversation, with 2 agents, one for code generation and one for code improvement
# - code generation agent should generate code for the task
# - code improvement agent should improve the code generated by the code generation agent

# 3. create 3rd allignment agent to align the code generation to the prime directive

# 4. create llama guard agent, with prompt guard for security, to prevent malicious code generation, or rogue ai agent behavior
# - the llama guard agent should be able to prevent malicious code generation, or rogue ai agent behavior